/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as PublicContactsRouteImport } from './routes/_public/contacts'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthSetPasswordIndexRouteImport } from './routes/auth/set-password/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthMagicLinkIndexRouteImport } from './routes/auth/magic-link/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSessionsIndexRouteImport } from './routes/admin/sessions/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as PublicProfileIndexRouteImport } from './routes/_public/profile/index'
import { Route as PublicNotificationsIndexRouteImport } from './routes/_public/notifications/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminSettingsSecurityRouteImport } from './routes/admin/settings/security'
import { Route as AdminSettingsProfileRouteImport } from './routes/admin/settings/profile'
import { Route as AdminSettingsPreferencesRouteImport } from './routes/admin/settings/preferences'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicContactsRoute = PublicContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetPasswordIndexRoute = AuthSetPasswordIndexRouteImport.update({
  id: '/set-password/',
  path: '/set-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkIndexRoute = AuthMagicLinkIndexRouteImport.update({
  id: '/magic-link/',
  path: '/magic-link/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSessionsIndexRoute = AdminSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicProfileIndexRoute = PublicProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNotificationsIndexRoute =
  PublicNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsPreferencesRoute =
  AdminSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/contacts': typeof PublicContactsRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/settings/preferences': typeof AdminSettingsPreferencesRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/notifications': typeof PublicNotificationsIndexRoute
  '/profile': typeof PublicProfileIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/magic-link': typeof AuthMagicLinkIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/set-password': typeof AuthSetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/contacts': typeof PublicContactsRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/settings/preferences': typeof AdminSettingsPreferencesRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/notifications': typeof PublicNotificationsIndexRoute
  '/profile': typeof PublicProfileIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/magic-link': typeof AuthMagicLinkIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/set-password': typeof AuthSetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/_public/contacts': typeof PublicContactsRoute
  '/api/$': typeof ApiSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/settings/preferences': typeof AdminSettingsPreferencesRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_public/notifications/': typeof PublicNotificationsIndexRoute
  '/_public/profile/': typeof PublicProfileIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/magic-link/': typeof AuthMagicLinkIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/set-password/': typeof AuthSetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/admin/settings'
    | '/contacts'
    | '/api/$'
    | '/'
    | '/admin/'
    | '/auth/'
    | '/admin/settings/preferences'
    | '/admin/settings/profile'
    | '/admin/settings/security'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/notifications'
    | '/profile'
    | '/admin/categories'
    | '/admin/sessions'
    | '/admin/settings/'
    | '/admin/users'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contacts'
    | '/api/$'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/settings/preferences'
    | '/admin/settings/profile'
    | '/admin/settings/security'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/notifications'
    | '/profile'
    | '/admin/categories'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/admin/settings'
    | '/_public/contacts'
    | '/api/$'
    | '/_public/'
    | '/admin/'
    | '/auth/'
    | '/admin/settings/preferences'
    | '/admin/settings/profile'
    | '/admin/settings/security'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_public/notifications/'
    | '/_public/profile/'
    | '/admin/categories/'
    | '/admin/sessions/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/auth/magic-link/'
    | '/auth/reset-password/'
    | '/auth/set-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/contacts': {
      id: '/_public/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PublicContactsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/set-password/': {
      id: '/auth/set-password/'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/magic-link/': {
      id: '/auth/magic-link/'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/sessions/': {
      id: '/admin/sessions/'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/profile/': {
      id: '/_public/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/notifications/': {
      id: '/_public/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof PublicNotificationsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/profile': {
      id: '/admin/settings/profile'
      path: '/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/preferences': {
      id: '/admin/settings/preferences'
      path: '/preferences'
      fullPath: '/admin/settings/preferences'
      preLoaderRoute: typeof AdminSettingsPreferencesRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicContactsRoute: typeof PublicContactsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicNotificationsIndexRoute: typeof PublicNotificationsIndexRoute
  PublicProfileIndexRoute: typeof PublicProfileIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicContactsRoute: PublicContactsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicNotificationsIndexRoute: PublicNotificationsIndexRoute,
  PublicProfileIndexRoute: PublicProfileIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsPreferencesRoute: typeof AdminSettingsPreferencesRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsPreferencesRoute: AdminSettingsPreferencesRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminSessionsIndexRoute: typeof AdminSessionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminSessionsIndexRoute: AdminSessionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthMagicLinkIndexRoute: typeof AuthMagicLinkIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSetPasswordIndexRoute: typeof AuthSetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthMagicLinkIndexRoute: AuthMagicLinkIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSetPasswordIndexRoute: AuthSetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
